name: Build BandTOTP APK

on:
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    name: Build BandTOTP APK
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout BandTOTP-Android Repository
        uses: actions/checkout@v3
        with:
          repository: Dustbin-lst/BandTOTP-Android
          path: BandTOTP-Android

      # 2. 设置 JDK 环境
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      # 3. 下载并安装 Android SDK
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d $HOME/android-sdk
          rm sdk-tools.zip
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # 4. 构建 APK
      - name: Build APK
        run: |
          cd BandTOTP-Android
          chmod +x ./gradlew
          ./gradlew clean assembleDebug

      # 5. 上传生成的 APK 文件
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: BandTOTP-Android-debug-apk
          path: BandTOTP-Android/app/build/outputs/apk/debug/*.apk
