name: Build BandTOTP APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build BandTOTP APK
    runs-on: ubuntu-22.04  # ARM64 基于 Ubuntu 的环境
    container: arm64v8/openjdk:11  # ARM64 OpenJDK 镜像

    steps:
      # 1. 克隆代码仓库
      - name: Clone BandTOTP-Android Repository
        run: |
          git clone https://github.com/Dustbin-lst/BandTOTP-Android.git
          cd BandTOTP-Android

      # 2. 设置 Java 环境
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          architecture: arm64

      # 3. 下载并安装 Android SDK
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d $HOME/android-sdk
          rm sdk-tools.zip
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # 4. 构建 APK
      - name: Build APK
        run: |
          cd BandTOTP-Android
          chmod +x ./gradlew
          ./gradlew clean assembleDebug

      # 5. 上传生成的 APK 文件
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: BandTOTP-Android-debug-apk
          path: BandTOTP-Android/app/build/outputs/apk/debug/*.apk
