name: Build Armbian By Self

on:
  workflow_dispatch:
    inputs:
      RELEASE:
        type: choice
        description: '选择发行版'
        required: true
        default: 'nobe'  # 默认值
        options:
          - oracular  # Ubuntu 24.10
          - noble     # Ubuntu 24.04
          - jammy     # Ubuntu 22.04 LTS
          - bookworm  # Debian 12
          - bullseye  # Debian 11
          - sid       # Debian unstable
          - trixie    # Debian Trixe

      armbian_mini:
        description: '是否选择minimal版(no/yes)'

jobs:
  build:
    runs-on: self-hosted
    steps:

    - name: Initialization environment
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt -y update
        sudo -E apt -y upgrade
        sudo -E apt clean
        echo "status=success" >> ${GITHUB_OUTPUT}

    # 检查空间使用情况
    - name: Check space usage
      run: df -hT

    # 克隆源码
    - name: Clone source code
      run: git clone --single-branch --depth=1 --branch=main https://github.com/armbian/build.git

    # 开始构建
    - name: Armbian build
      run: |
        cd build
        sudo ./compile.sh \
          BOARD=hinlink-ht2 \
          BRANCH=vendor \
          KERNEL_TARGET='vendor' \
          RELEASE=${{ github.event.inputs.RELEASE }} \
          BUILD_MINIMAL=${{ github.event.inputs.armbian_mini }} \
          BUILD_DESKTOP=no \
          KERNEL_CONFIGURE=no \
          EXPERT=yes \
          USE_CONTAINER=no \
          COMPRESS_OUTPUTIMAGE=img

    # 检查空间使用情况
    - name: Check space usage
      run: df -hT

    # 上传构建结果
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Armbian-${{ github.event.inputs.RELEASE }}-mini${{ github.event.inputs.armbian_mini }}
        path: build/output/images/
