name: Build Armbian

on:
  workflow_dispatch:
    inputs:
      RELEASE:
        type: choice
        description: '选择发行版'
        required: true
        default: 'nobe'  # 默认值
        options:
          - oracular  # Ubuntu 24.10
          - noble     # Ubuntu 24.04
          - jammy     # Ubuntu 22.04 LTS
          - bookworm  # Debian 12
          - bullseye  # Debian 11
          - sid       # Debian unstable
          - trixie    # Debian Trixe

      armbian_mini:
        description: '是否选择minimal版'
        options:
          - no
          - yes
        default: no
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # 初始化环境
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          curl \
          wget \
          flex \
          bison \
          gawk \
          gcc \
          g++ \
          make \
          libc6-dev \
          libncurses5-dev \
          libssl-dev \
          qemu-user-static \
          debootstrap \
          libxml2-utils \
          rsync \
          zip \
          unzip \
          bc \
          device-tree-compiler \
          u-boot-tools \
          pv \
          python3 \
          python3-serial \
          python3-pip \
          dosfstools \
          mtools \
          parted \
          liblz4-tool \
          lzop \
          zstd

    # 检查空间使用情况
    - name: Check space usage
      run: df -hT

    # 开始构建
    - name: Armbian build
      run: |
        git clone --depth=1 --branch=main https://github.com/armbian/build.git
        cd build
        ./compile.sh \
          BOARD=hinlink-ht2 \
          BRANCH=vendor \
          KERNEL_TARGET='vendor' \
          RELEASE=${{ github.event.inputs.RELEASE }} \
          BUILD_MINIMAL=${{ github.event.inputs.armbian_mini }} \
          BUILD_DESKTOP=no \
          KERNEL_CONFIGURE=no \
          COMPRESS_OUTPUTIMAGE=img

    # 检查空间使用情况
    - name: Check space usage
      run: df -hT

    # 上传构建结果
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Armbian-${{ github.event.inputs.RELEASE }}-mini${{ github.event.inputs.armbian_mini }}
        path: build/output/images/
